import { describe, expect, it } from 'vitest'
import { ScreenBuffer } from '../src/screen-buffer.ts'

describe('ScreenBuffer CSI coverage', () => {
  it('handles cursor moves, tabs, backspace, and EL modes', () => {
    const screen = new ScreenBuffer(16, 4)
    screen.write('abcd')
    screen.write('\b\b')
    screen.write('XY')
    screen.write('\t')
    screen.write('z')
    screen.write('\r')
    screen.write('!')
    expect(screen.snapshot().lines[0]!.startsWith('!')).toBe(true)
    screen.write('\x1b[2K')
    expect(screen.snapshot().lines[0]!.trim()).toBe('')
    screen.write('row')
    screen.write('\x1b[1K')
    screen.write('\x1b[0K')
    screen.write('\x1b[A\x1b[B\x1b[C\x1b[D')
    screen.write('\x1b[1;1H')
    screen.write('\x1b[1;2f')
    screen.write('\x1b[?1J')
    screen.write('\x1b[3J')
    expect(screen.snapshot().lines.every(line => line.trim() === '')).toBe(true)
  })

  it('handles OSC sequences and ignored controls', () => {
    const screen = new ScreenBuffer(20, 3)
    screen.write('\x1b]0;title\x07')
    screen.write('\x1b]0;title\x1b\\')
    screen.write('\x1bZ')
    screen.write('\x01')
    screen.write('ok')
    expect(screen.snapshot().lines[0]).toContain('ok')
  })

  it('clears forward and wraps at the edge', () => {
    const screen = new ScreenBuffer(4, 3)
    screen.write('1234')
    expect(screen.snapshot().cursorRow).toBeGreaterThanOrEqual(0)
    screen.write('\x1b[1;1H')
    screen.write('\x1b[0J')
    screen.write('a')
    screen.write('\x1b[1;1Hxx')
    screen.write('\x1b[1J')
    screen.write('\n\n\n')
    const snap = screen.snapshot()
    expect(snap.lines.length).toBe(3)
  })

  it('rejects chromatic selection paint as the input bar', () => {
    const screen = new ScreenBuffer(16, 3)
    screen.write('\x1b[42m........\x1b[m')
    const snap = screen.snapshot()
    expect(snap.barBgRows[0]).toBe(false)
    expect(snap.accentRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;2;0;160;0m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(false)
    expect(screen.snapshot().accentRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;2;0;10;0m........\x1b[m')
    expect(screen.snapshot().accentRows[0]).toBe(false)
  })

  it('detects a short gray pill on a wide PTY', () => {
    const screen = new ScreenBuffer(100, 4)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;2;58;58;62m→ /\x1b[49m\n')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
  })

  it('applies Ink-style CHA, IL/DL, ICH/DCH, scroll, and save/restore', () => {
    const screen = new ScreenBuffer(8, 4)
    screen.write('abcd')
    screen.write('\x1b[s')
    screen.write('\x1b[1;1H')
    screen.write('\x1b[2@')
    screen.write('\x1b[2P')
    screen.write('\x1b[u')
    screen.write('\x1b7')
    screen.write('\x1b[2;1H')
    screen.write('\x1b8')
    screen.write('\x1b[1G')
    screen.write('\x1b[1E')
    screen.write('x')
    screen.write('\x1b[1F')
    screen.write('\x1b[2d')
    screen.write('\x1b[1L')
    screen.write('\x1b[1M')
    screen.write('\x1b[1S')
    screen.write('\x1b[1T')
    screen.write('\x1b[0G')
    screen.write('\x1b[0d')
    screen.write('\x1b[0E')
    screen.write('\x1b[0F')
    screen.write('\x1b[0L')
    screen.write('\x1b[0M')
    screen.write('\x1b[0P')
    screen.write('\x1b[0@')
    screen.write('\x1b[0S')
    screen.write('\x1b[0T')
    screen.write('\x1b[4J')
    screen.write('\x1b[48:2:x:1:2m')
    screen.write('\x1b[48;5;16m.')
    screen.write('\x1b[4;8H')
    screen.write('\x1b[s')
    screen.resize(4, 2)
    screen.write('\x1b[u')
    expect(screen.snapshot().lines.length).toBe(2)
  })

  it('defers wrap so a full-width slash row plus CRLF does not skip a line', () => {
    const screen = new ScreenBuffer(10, 5)
    screen.write('\x1b[2J\x1b[H')
    // Previous frame left /ask on the second menu row.
    screen.write('other-row!\r\n')
    screen.write('/askXXXXXX\r\n')
    screen.write('after-ask!\r\n')
    // Ink rewrites from the first row: exact-width line, no EL, then CRLF.
    screen.write('\x1b[1;1H')
    screen.write('AAAAAAAAAA')
    screen.write('\r\n')
    screen.write('BBBB\r\n')
    const lines = screen.snapshot().lines
    expect(lines[0]).toBe('AAAAAAAAAA')
    expect(lines[1]!.startsWith('BBBB')).toBe(true)
    expect(lines.some(line => line.includes('/ask'))).toBe(false)
    // Next printable after a full-width write performs the deferred wrap.
    screen.write('\x1b[2J\x1b[H')
    screen.write('CCCCCCCCCC')
    screen.write('D')
    expect(screen.snapshot().lines[0]).toBe('CCCCCCCCCC')
    expect(screen.snapshot().lines[1]!.startsWith('D')).toBe(true)
  })

  it('drops leftover menu rows on erase-down after a shorter redraw', () => {
    const screen = new ScreenBuffer(40, 8)
    screen.write('\x1b[2J\x1b[H')
    screen.write('→ /\n')
    screen.write('→ /model [filter]           Select model\n')
    screen.write('     /ask                      Toggle ask\n')
    screen.write('\x1b[H')
    screen.write('→ hi\n')
    screen.write('\x1b[J')
    const lines = screen.snapshot().lines.filter(line => line.trim().length > 0)
    expect(lines.some(line => line.includes('/model'))).toBe(false)
    expect(lines.some(line => line.includes('hi'))).toBe(true)
  })

  it('applies SGR reverse and reset', () => {
    const screen = new ScreenBuffer(10, 2)
    screen.write('\x1b[7mHi\x1b[27m!\x1b[m')
    const snap = screen.snapshot()
    expect(snap.reverseRows[0]).toBe(true)
  })

  it('tracks elevated gray bar backgrounds from 256-color and RGB SGR', () => {
    const screen = new ScreenBuffer(16, 3)
    screen.write('\x1b[48;5;236m........\x1b[49m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;2;58:58:62m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[40m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(false)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[47m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[100m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[107m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;5;7m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;5;8m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;5;15m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;5;9m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(false)
    expect(screen.snapshot().accentRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;5;232m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(false)
    expect(screen.snapshot().accentRows[0]).toBe(false)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;5;102m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[48;5;46m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(false)
    expect(screen.snapshot().accentRows[0]).toBe(true)
    screen.write('\x1b[2J\x1b[H')
    screen.write('\x1b[41m........\x1b[m')
    expect(screen.snapshot().barBgRows[0]).toBe(false)
    expect(screen.snapshot().accentRows[0]).toBe(true)
  })

  it('ignores unknown CSI finals and scrolls on wrap/line feed', () => {
    const screen = new ScreenBuffer(2, 2)
    screen.write('\x1b[999Z')
    screen.write('abcdef')
    screen.write('\n\n')
    expect(screen.snapshot().lines.length).toBe(2)
    screen.write('\x1b]1;x\x1b')
    screen.write('[2J')
    screen.write('\x1b[2;2H')
    screen.write('\x1b[1J')
    expect(screen.snapshot().lines.length).toBe(2)
  })

  it('covers CUP without column, empty SGR, and unrelated SGR codes', () => {
    const screen = new ScreenBuffer(8, 4)
    screen.write('abcd')
    screen.write('\x1b[3H')
    screen.write('x')
    screen.write('\x1b[m')
    screen.write('\x1b[1m')
    screen.write('\x1b[38;5;1m')
    screen.write('\x1b[38;2;1;2;3m')
    screen.write('\x1b[38m')
    screen.write('\x1b[48m')
    screen.write('\x1b[48;5m')
    screen.write('\x1b[48;2;1;2m')
    screen.write('\x1b[3J')
    screen.write('\x1b[A')
    expect(screen.snapshot().lines.length).toBe(4)
  })
})
